var GAME_LEVELS = [
  ["xxxxxxxxxxxxxxxxxxxxxxxxxx                                                     x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxx                                                     x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxx                                                     x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxx                                                     x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxx                                                     x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxx                                                     x",
   "                    vv                                                        fx",
   "                                                                              xx",
   "                         o o o          o     o                 o   o   o    xxx",
   "                       xxxxxxxx    xxxxxxxxxxxxxxxx  00  xxx    0   0   0  xxxxx",
   "                  o                   |    xxxxxxxx      xxx                 xxx",
   "                 xxx                       xxxxxxxx      xxx                 xxx",
   "                       o o o               xxxxxxxx!!!!!!xxx!!!!!!!!!!!!!!!!!xxx",
   "                      xxxxxxx              xxxxxxxx!!!!!!xxx!!!!!!!!!!!!!!!!!xxx",
   "                                x        ooxxxxxxxx!!!!!!xxx!!!!!!!!!!!!!!!!!xxx",
   "                                     |   ooxxxxxxxx!!!!!!xxx!!!!!!!!!!!!!!!!!xxx",
   "                                   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "  @                               xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxx       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxx    o    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxx    x    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxx         xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!|!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!                                                                             !",
   "!!                                                                             !",
   "!!                                     oooooo            oooooo                !",
   "!!                                                                             !",
   "!!                    ooooo                                                    !",
   "!!                                               xxxxx            xxxx         !",
   "!!ooo                                                                          !",
   "!!xxxx   xxxxxxxxxx           xxxxx                                00          !",
   "!!xxxx   xxxxxxxxxx                                                            !",
   "!!xx |     xxxxxx                         !                                    !",
   "!!xx       xxxxxx                                                         oooo !",
   "!!xx       xxxxxx                                           xxxxxxxxxxxxxxxxxxx!",
   "!!xx       xxxxxx                                        xxxxxxxxxxxxxxxxxxxxxx!",
   "!!xx       xxxxxx                                           !!!!!!!!!!!!!!!!!!!!",
   "!!xx   f | xxxxxx                                         0 !!!!!!!!!!!!!!!!!!!!",
   "xxxxxxxxxxxxxxxxx                o o o             oo       !!!!!!!!!!!!!!!!!!!!",
   "x         v    v                         o                  !!!!!!!!!!!!!!!!!!!!",
   "x                                          o                !!!!!!!!!!!!!!!!!!!!",
   "x                     xxxxxxxx             00       xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "x                     xxxxxxx0                        xxxxxxxxxxxxxxxxxxxxxxxxxx",
   "x  @        oo  xxx   xxxxxxxo          =x           =xxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxx  xx  xxx!!!xxxxxxx                         xxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxx!!!!!!xxx!!!xxxxxxx                         xxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxx!!!!!!xxxxxxxxxxxxxx=          x=           xxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxx!!!!!!xxxxxxxxxxxxxx                        xxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxx!!!!!!xxxxxxxxxxxxxxx    o    o     o    > xxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxx!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "!                  |             ||||||||||||||||||||||||||||||||||||||||||||xxx",
   "!                                                                            xxx",
   "!                                                                            xxx",
   "!                  ooo                                                       xxx",
   "!                 xxxxx                                                      xxx",
   "!>                    xxxxx      ooooooooooooooooooooooooooooooooooooooooooofxxx",
   "xxxxxxxx                 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "x                           xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "x        0                     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "x                                 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "x                                        |              v  v  v               xx",
   "x           00                                                                xx",
   "x               0                                                             xx",
   "x                  00                                                         xx",
   "x                      00                                                     xx",
   "x                                                                             xx",
   "x!!!!!!!!!!!!!!!!!!!!!!!!!xxxx                                                xx",
   "x!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxx                   x                        xx",
   "x!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxx    |     0                             xx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx           x                     xx",
   "x           |       |       |       |       |                                 xx",
   "x                                                          x          o o o   xx",
   "x                                                                    o o o o  xx",
   "x                                                             x       o o o   xx",
   "x                                                                    o o o o  xx",
   "x         o   o   o   o   o   o   o   o   o   o                  xxxxxxxxxxxxxxx",
   "x                                                                xxxxxxxxxxxxxxx",
   "x                                                         xxxxxxxxxxxxxxxxxxxxxx",
   "x @             |       |       |       |          o  o   xxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxx!   x=  x  =x=  x  =x=  x  =x=  x  =x   !xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxx!                                       !xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxx!                                       !xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["                        ",
   "  xx   x xxxxx x   x  x ",
   "   x   x x   x x   x  x ",
   "   x   x x   x x   x  x ",  
   "   xxxxx x   x x   x  x ",
   "       x xxxxx xxxxx  x ",
   "       x              x ",
   "     xxx              x ",
   "                      x ",
   " xx     x xxxxx x   x x ",
   "  x     x   x   xx  x x ",
   "  x  x  x   x   x x x   ",
   "  x  x  x   x   x  xx ! ",
   "  xxxxxxx xxxxx x   x ! ",
   "	     			    "],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
